### Задание 1

In [111]:
import numpy as np

In [112]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1,7]])

In [113]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [114]:
mean_a = np.mean(a, axis = 0)

In [115]:
mean_a

array([2. , 8.4])

In [116]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

### Задание 2

In [117]:
a_centered = a - mean_a

In [118]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [119]:
k = 0
a_centered_sp = 0
while k < 5:
    a_centered_sp = a_centered[k, 0] * a_centered[k, 1] + a_centered_sp
    k = k + 1

In [120]:
a_centered_sp

8.0

In [121]:
res = a_centered_sp / (len(a) - 1)

In [122]:
res

2.0

### Задание 4

In [123]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])